# Generated by Django 3.2.5 on 2022-03-18 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('organisation', models.CharField(max_length=255)),
                ('cert', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.TextField()),
                ('image', models.TextField()),
                ('ttf', models.TextField()),
                ('cert', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('signed_date', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptographie.document')),
            ],
        ),
    ]
