# Generated by Django 3.2.5 on 2022-04-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csrgenerator', '0003_cert_user'),
        ('cryptographie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csrgenerator.cert'),
        ),
        migrations.AlterField(
            model_name='signataire',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csrgenerator.cert'),
        ),
        migrations.AlterField(
            model_name='signataire',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='signataire',
            name='ttf',
            field=models.TextField(default=''),
        ),
    ]
