# Generated by Django 3.2.5 on 2022-04-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0002_auto_20220406_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signataire',
            name='document',
        ),
    ]
