# Generated by Django 3.2.5 on 2022-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0005_alter_signataire_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='signataire',
            name='nom_complet',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
