# Generated by Django 3.2.5 on 2022-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0006_signataire_nom_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signataire',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signataire',
            name='ttf',
            field=models.TextField(),
        ),
    ]
