# Generated by Django 3.2.5 on 2022-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0007_auto_20220411_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nombre',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='signataire',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
    ]
