# Generated by Django 3.2.5 on 2022-04-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0008_auto_20220425_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='nombre',
            new_name='nombre_signataire',
        ),
    ]
