# Generated by Django 3.2.5 on 2022-05-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0009_rename_nombre_document_nombre_signataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='ttf',
            field=models.TextField(default=''),
        ),
    ]
