# Generated by Django 3.2.5 on 2022-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0010_auto_20220503_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='signataire',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
