# Generated by Django 3.2.5 on 2022-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0012_personal_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signataire',
            name='file_hash',
            field=models.TextField(default=''),
        ),
    ]
