# Generated by Django 3.2.5 on 2022-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographie', '0013_auto_20220808_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_signature_image',
            old_name='image',
            new_name='image_data',
        ),
        migrations.AddField(
            model_name='personal_signature_image',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
