# Generated by Django 3.2.3 on 2021-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255, null=True)),
                ('localite', models.CharField(max_length=255, null=True)),
                ('organisation', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('pass_phrase', models.TextField()),
                ('key_size', models.IntegerField()),
                ('nom_cert', models.TextField()),
                ('nom_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
