# Generated by Django 3.2.5 on 2022-08-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_2_base', models.TextField()),
                ('port', models.TextField(null=True)),
                ('signataire_url', models.TextField()),
                ('OTP_time_validity', models.IntegerField()),
                ('before_signature_alert_message_subject', models.TextField()),
                ('before_signature_alert_message', models.TextField()),
                ('signedFile_alert_sending_subject', models.TextField()),
                ('signedFile_alert_sending_message', models.TextField()),
            ],
        ),
    ]
