# Generated by Django 3.2.5 on 2022-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_parameters',
            name='signature_certificat_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='default_parameters',
            name='signature_certificat_objet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='default_parameters',
            name='signature_certificat_template_url',
            field=models.TextField(default=''),
        ),
    ]
