# Generated by Django 3.2.5 on 2022-07-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('username', models.TextField(null=True)),
                ('password', models.TextField()),
                ('key', models.TextField()),
                ('server_url', models.TextField(default='smtp.gmail.com')),
                ('port', models.IntegerField()),
                ('protocole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailling.protocole')),
            ],
        ),
    ]
